const constants = {
  ADD_EXPRESSION: "ADD_EXPRESSION",
  REMOVE_EXPRESSION: "REMOVE_EXPRESSION",
  UPDATE_EXPRESSION: "UPDATE_EXPRESSION",
  INCREMENT_HISTORY_DELETED_COUNTER: "INCREMENT_HISTORY_DELETED_COUNTER",
  RESET_HISTORY_DELETED_COUNTER: "RESET_HISTORY_DELETED_COUNTER",
  UPDATE_SETTING: "UPDATE_SETTING",
  RESET_SETTINGS: "RESET_SETTINGS"
};

export default constants;
